### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/nettlesnotions#2]
### **User Story**
---
As a user when I visit this site I should come to a landing page. On this page I would see a background image a link that when clicked will bring me to the blog page(filler for future ticket). I would also see a logo with the title of the blog page at the top and a basic introduction to the person of interest on the site as well as the contents of the site.

### **AC**
---
**When** the user visits the site they should see a landing page
**They** should also see a logo and the title of the site somewhere at the top of the page
**There** should be a link that will redirect the user to the blog page of the site
**They** should also see and be able to read a small introductory to the blogger and the contents of the site
**They** should see that the page is visually pleasing(styled) so as to draw the user in

### **To-Do**
---

- [ ]  Create component folder for landing page
- [ ]  Create files for page( .js and .scss )
- [ ]  Create render function
- [ ] the function should render some jsx
- [ ] in the render create a container that houses the landing page
